#!/bin/bash
# 全ケースを実行する:
# USAGE: ./test

# 1ケースだけ実行する:
# USAGE: ./test empty

# コンパイラの標準入出力は test_stdout.md/test_stderr.md に出力される。

set -eu

f() {
    NAME=$1
    SRC="tests/$NAME/$NAME.jacco"

    echo 'test: '$SRC
    echo -e '\n## test: '$SRC'\n\n```' | tee -a test_stderr.md >>test_stdout.md
    cargo run --bin jl_tests "$SRC" \
        1> >(tee -a test_stdout.md >&2) \
        2> >(tee -a test_stderr.md | grep -E 'Compiling|panicked|error|ERROR|\.rs\:' 1>&2)
    echo '```' | tee -a test_stderr.md >>test_stdout.md
}

f_all() {
    f empty
    f exit_with_42
    f extern_fn
    f add
    f arithmetic
    f if
    f let
    f operators
    f complex
    f while
    f loop
    f break
    f continue
    f call_direct
    f return
    f syntax_error
    f assign
    f unit_like_struct
    f record_struct
    f char
    f bool
    f cast
    f int_types
    f str
    f ptr
}

ONLY=${1:-''}

: >test_stdout.md
: >test_stderr.md

if ! test -z $ONLY
then
    f $ONLY
else
    f_all
fi

# 差分の量を表示する。
git --no-pager diff --stat --relative -- 'tests/*/*.txt'
