#!/bin/bash

set -eu

test -x c_compiler

assert() {
    EXPECTED="$1"
    INPUT="$2"

    ./c_compiler "$INPUT" >actual.s || {
        echo "\$?=$? (actual.s)" >&2
        exit 1
    }

    gcc actual.s -o actual.out || {
        echo "\$=$? (actual.out)" >&2
        exit 1
    }
    ./actual.out && ACTUAL=$? || ACTUAL=$?
    echo "$INPUT => $ACTUAL"

    if test $ACTUAL -ne $EXPECTED
    then
        echo "$INPUT => $EXPECTED expected, but got $ACTUAL" >&2
        exit 1
    fi
}

assert 0 0
assert 42 42

echo OK >&2
