#!/bin/bash

set -eu

JACCO_BIN=${JACCO_BIN:-'../../target/debug/jacco'}

NAME=$(basename $(pwd))

CFLAGS='-std=c11 -Wall -Wno-unused-variable -Wno-unused-but-set-variable'
SRCS="$NAME.jacco.c $NAME.c"

RUST_LOG=warn "$JACCO_BIN" build "$NAME.jacco" >"$NAME.jacco.c"

gcc $CFLAGS $SRCS -o "./$NAME"

assert() {
    EXPECTED="$1"
    INPUT="$2"

    "./$NAME" "$INPUT" >actual.s || {
        echo "\$?=$? (actual.s)" >&2
        exit 1
    }

    gcc actual.s -o actual.out || {
        echo "\$=$? (actual.out)" >&2
        exit 1
    }
    ./actual.out && ACTUAL=$? || ACTUAL=$?
    echo "$INPUT => $ACTUAL"

    if test $ACTUAL -ne $EXPECTED
    then
        echo "$INPUT => $EXPECTED expected, but got $ACTUAL" >&2
        exit 1
    fi
}

assert 0 0
assert 42 42

echo OK >&2
